image: gradle:alpine

stages:
  - format_s1
  - build_s1
  - test_s1

format_s1:
  stage: format_s1
  variables:
    s1_dir: "./Sprint-1"
    GRADLE_USER_HOME: "./Sprint-1/.gradle"
  script:
    - cd $s1_dir
    - export GRADLE_USER_HOME
    - gradle spotlessApply
    # Check if formatting changed anything
    - |
      if ! git diff --quiet; then
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Bot"
        git remote set-url --push origin $CI_REPOSITORY_URL
        git add .
        git commit -m "[BOT] Apply Spotless formatting"
        git push origin HEAD:$CI_COMMIT_REF_NAME
      fi

build_s1:
  stage: build_s1
  variables:
    s1_dir: "./Sprint-1"
    GRADLE_USER_HOME: "./Sprint-1/.gradle"
  script:
    - cd $s1_dir
    - export GRADLE_USER_HOME
    - gradle jar

test_s1:
  stage: test_s1
  variables:
    s1_dir: "./Sprint-1"
    GRADLE_USER_HOME: "./Sprint-1/.gradle"
  script:
    - cd $s1_dir
    - export GRADLE_USER_HOME
    - gradle test